services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: thrive_cart
    environment:
      - IS_SPECIAL_OFFER_ACTIVE=${IS_SPECIAL_OFFER_ACTIVE:-false}
    ports:
      - "${APP_PORT:-8080}:80"
    networks:
      - thrive
    volumes:
      - ".:/var/www/html"
      - ./startup.sh:/usr/local/bin/startup.sh:ro
networks:
  thrive:
    driver: bridge
