name: Thrive Cart

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  app-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.3`"
          extensions: dom, curl, libxml, mbstring, zip
          tools: composer:v2
          coverage: none
      - uses: actions/checkout@v3
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install --prefer-dist
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: composer test
      - name: PHPStan
        run: composer phpstan
